services:
  cktefrei_bdd:
    container_name: cktefrei_bdd
    image: mariadb:12.1.2
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: bddname
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 5

  cktefrei_adminer:
    container_name: cktefrei_adminer
    image: adminer
    ports:
      - 8080:8080

  cktefrei_backend_build:
    container_name: cktefrei_backend_build
    build: ./backend/.
    environment:
      BDD_HOST: cktefrei_bdd
    ports:
      - 12000:12000
    depends_on:
      cktefrei_bdd:
        condition: service_healthy