name: 01-1 - Integration - TEST

on:
  workflow_call

jobs:
  Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: toor
          MARIADB_DATABASE: test
          MARIADB_USER: test
          MARIADB_PASSWORD: test
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      BDD_HOST: 127.0.0.1
      BDD_PASS: test
      BDD_NAME: test
      BDD_USER: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Database Cnx Check
        run: |
          sudo apt-get install -y mariadb-client
          mysql --host 127.0.0.1 --port 3306 -u root -ptoor -e "SHOW DATABASES;"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Backend Dependencies
        run: npm install

      - name: Init bdd
        run: npm run initbdd

      - name: Populate bdd
        run: |
          mysql -u root -ptoor --host 127.0.0.1 --port 3306 --database test < ./test/insert_test_user.sql

      - name: Run Backend Tests
        run: npm run test:cov

      - name: Upload Backend Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/coverage
          retention-days: 1

  Frontend:
    needs: [Backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start HotBuild Backend
        run: |
          cd ..
          cp ./_tools/docker/docker-compose-back-build.yml .
          docker compose -f docker-compose-back-build.yml up -d
          docker ps -a

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Test Backend COntainer
        if: success()
        run: curl http://127.0.0.1:12000

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Cypress E2E Install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: ./frontend

      - name: Install Frontend Dependencies
        run: npm install

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: ./frontend
          start: npm run dev

      - name: Cypress Test and Coverage
        run: npm run cypress:cov

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ./frontend/cypress/screenshots
          retention-days: 1

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: ./frontend/cypress/videos
          retention-days: 1

      - name: Upload Frontend Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: frontend/coverage
          retention-days: 1

      - name: Shutdown HotBuild Backend
        if: always()
        run: |
          cd ../_tools/docker
          docker compose -f docker-compose-back-build.yml down