name: 02-3 - Deploy - Staging

on:
  workflow_call

jobs:
  AzureStagingServer:
    runs-on: ubuntu-latest
    environment: STAGING

    env:
      ResourceGroupName: "jenpeuplus-staging-vm"
      ResourceGroupLocation: "westeurope"

    steps:
      - name: 1. Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 2. Azure CLI Create RG
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az group create --name ${{env.ResourceGroupName}} --location ${{env.ResourceGroupLocation}}

#      - name: 3. Azure CLI Deploy ARM
#        uses: azure/arm-deploy@v2
#        with:
#          resourceGroupName: ${{env.ResourceGroupName}}
#          scope: resourcegroup
#          template: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/refs/heads/master/quickstarts/microsoft.compute/vm-simple-linux/azuredeploy.json
#          parameters: adminUsername=${{ secrets.AZURE_VM_LOGIN }} adminPasswordOrKey=${{ secrets.AZURE_VM_PASSWORD }} vmName=jenpeuplus-staging-vm location=${{ env.ResourceGroupLocation }} vmSize=Standard_B2s

      - name: 3. Deploy VM via CLI (Sans Template)
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az vm create \
              --resource-group ${{ env.ResourceGroupName }} \
              --name "jenpeuplus-staging-vm" \
              --image Ubuntu2204 \
              --size Standard_B2s \
              --admin-username ${{ secrets.AZURE_VM_LOGIN }} \
              --admin-password ${{ secrets.AZURE_VM_PASSWORD }} \
              --public-ip-sku Standard \
              --assign-identity

      - name: 4. Open Port on Security Group
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az network nsg rule create --resource-group ${{env.ResourceGroupName}} --nsg-name SecGroupNet --name PortBack-12000 --priority 100 --direction Inbound --access Allow --protocol Tcp --source-address-prefixes "*" --source-port-ranges "*" --destination-address-prefixes "*" --destination-port-ranges 12000
            az network nsg rule create --resource-group ${{env.ResourceGroupName}} --nsg-name SecGroupNet --name PortFront-80 --priority 101 --direction Inbound --access Allow --protocol Tcp --source-address-prefixes "*" --source-port-ranges "*" --destination-address-prefixes "*" --destination-port-ranges 80

      - name: 5. Get Public IP et créer règle
        if: success()
        uses: azure/CLI@v2
        with:
          inlineScript: |
            #!/bin/bash
            az vm show -d -g ${{env.ResourceGroupName}} -n jenpeuplus-staging-vm --query publicIps -o tsv
            echo "AZURE_VM_IP=$(az vm show -d -g ${{env.ResourceGroupName}} -n jenpeuplus-staging-vm --query publicIps -o tsv)" >> $GITHUB_ENV  

      - name: 6. Install Docker on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.AZURE_VM_IP}}
          port: ${{secrets.AZURE_PORT}}
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}
          script: |
            curl -o install_docker.sh https://raw.githubusercontent.com/azure-custom-cli/scripts/refs/heads/main/install_docker_ubuntu.sh
            ls -al
            bash ./install_docker.sh

      - name: 7. Set DNS Domain
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az network dns record-set a add-record -g JenPeuPlus-DNS -z staging.jenpeuplus.com -n cocktail -a ${{env.AZURE_VM_IP}}

      - name: 8. Checkout
        uses: actions/checkout@v3

      - name: 9. Update compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{env.AZURE_VM_IP}}
          port: ${{secrets.AZURE_PORT}}
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}

          source: "./_tools/docker/docker-compose.yml"
          target: "."

      - name: 10. Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: 11. Start compose file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.AZURE_VM_IP}}
          port: ${{secrets.AZURE_PORT}}
          username: ${{secrets.AZURE_VM_LOGIN}}
          password: ${{secrets.AZURE_VM_PASSWORD}}

          script: >
            echo ${{secrets.MONOREPO_PAT}} | docker login ghcr.io -u Floriansp40 --password-stdin


            echo MONO_PROJECT_BACK=ghcr.io/${{env.IMAGE_NAME_LOWER}}-back:canary > .env
            echo MONO_PROJECT_FRONT=ghcr.io/${{env.IMAGE_NAME_LOWER}}-front:canary >> .env

            chmod 600 .env

            docker pull ghcr.io/${{env.IMAGE_NAME_LOWER}}-back:canary
            docker pull ghcr.io/${{env.IMAGE_NAME_LOWER}}-front:canary

            docker compose up -d
